/**
 * Writes registry.go of the Go test, as Go cannot look up functions and constants by name: the
 * constructors of the classes of `statement` by the class name, and the constants of the AWS
 * managed policies by the name of the static property of TypeScript.
 *
 * Usage: registry.ts <managed-policies.json> <registry.go>
 */
import * as fs from 'fs';

const [managedPolicies, target] = process.argv.slice(2);

/**
 * The Go name of a static property, like the transpiler names it, e.g. `AmazonEC2FullAccess` →
 * `AwsManagedPolicy_AMAZON_EC2_FULL_ACCESS`
 */
function constantName(name: string): string {
  const snake = name
    .replace(/([\p{Ll}\d])(\p{Lu})/gu, '$1_$2')
    .replace(/(\p{Lu})(\p{Lu}\p{Ll}+)/gu, '$1_$2');
  return `AwsManagedPolicy_${snake.toUpperCase()}`;
}

const classes = fs
  .readdirSync('lib/generated/model')
  .filter((file) => file.endsWith('.json'))
  .sort()
  .map(
    (file) =>
      (
        JSON.parse(fs.readFileSync(`lib/generated/model/${file}`, 'utf8')) as {
          className: string;
        }
      ).className,
  );
classes.push('All');

const names = Object.keys(
  JSON.parse(fs.readFileSync(managedPolicies, 'utf8')) as Record<
    string,
    string
  >,
);

const lines = [
  '// Code generated by test/transpile/go/registry.ts. DO NOT EDIT.',
  '',
  'package main',
  '',
  'import (',
  '\t"udondan.github.io/iam-floyd/go/iamfloyd"',
  '\t"udondan.github.io/iam-floyd/go/iamfloyd/statement"',
  ')',
  '',
  'var classes = map[string]func(sid *string) any{',
  ...classes.map(
    (name) =>
      `\t${JSON.stringify(name)}: func(sid *string) any { return statement.New${name}(sid) },`,
  ),
  '}',
  '',
  'var managedPolicies = map[string]string{',
  ...names.map(
    (name) => `\t${JSON.stringify(name)}: iamfloyd.${constantName(name)},`,
  ),
  '}',
  '',
];
fs.writeFileSync(target, lines.join('\n'));
