import { PolicyStatement, Actions } from "./shared";

/**
 * Action provider for service transcribe
 *
 * https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazontranscribe.html
 */
export class Transcribe extends PolicyStatement {
    public servicePrefix = 'transcribe';
    public actions : Actions = {
        "CreateMedicalVocabulary": {
            "url": "https://docs.aws.amazon.com/transcribe/latest/dg/API_CreateMedicalVocabulary.html",
            "description": "Creates a new custom vocabulary that you can use to change the way Amazon Transcribe Medical handles transcription of an audio file.",
            "accessLevel": "Write"
        },
        "CreateVocabulary": {
            "url": "https://docs.aws.amazon.com/transcribe/latest/dg/API_CreateVocabulary.html",
            "description": "Creates a new custom vocabulary that you can use to change the way Amazon Transcribe handles transcription of an audio file.",
            "accessLevel": "Write"
        },
        "CreateVocabularyFilter": {
            "url": "https://docs.aws.amazon.com/transcribe/latest/dg/API_CreateVocabularyFilter.html",
            "description": "Creates a new vocabulary filter that you can use to filter out words from the transcription of an audio file generated by Amazon Transcribe",
            "accessLevel": "Write"
        },
        "DeleteMedicalTranscriptionJob": {
            "url": "https://docs.aws.amazon.com/transcribe/latest/dg/API_DeleteMedicalTranscriptionJob.html",
            "description": "Deletes a previously submitted medical transcription job.",
            "accessLevel": "Write"
        },
        "DeleteMedicalVocabulary": {
            "url": "https://docs.aws.amazon.com/transcribe/latest/dg/API_DeleteMedicalVocabulary.html",
            "description": "Deletes medical a vocabulary from Amazon Transcribe.",
            "accessLevel": "Write"
        },
        "DeleteTranscriptionJob": {
            "url": "https://docs.aws.amazon.com/transcribe/latest/dg/API_DeleteTranscriptionJob.html",
            "description": "Deletes a previously submitted transcription job along with any other generated results such as the transcription, models, and so on.",
            "accessLevel": "Write"
        },
        "DeleteVocabulary": {
            "url": "https://docs.aws.amazon.com/transcribe/latest/dg/API_DeleteVocabulary.html",
            "description": "Deletes a vocabulary from Amazon Transcribe.",
            "accessLevel": "Write"
        },
        "DeleteVocabularyFilter": {
            "url": "https://docs.aws.amazon.com/transcribe/latest/dg/API_DeleteVocabularyFilter.html",
            "description": "Deletes a vocabulary filter from Amazon Transcribe.",
            "accessLevel": "Write"
        },
        "GetMedicalTranscriptionJob": {
            "url": "https://docs.aws.amazon.com/transcribe/latest/dg/API_GetMedicalTranscriptionJob.html",
            "description": "Returns information about a medical transcription job.",
            "accessLevel": "Read"
        },
        "GetMedicalVocabulary": {
            "url": "https://docs.aws.amazon.com/transcribe/latest/dg/API_GetMedicalVocabulary.html",
            "description": "Gets information about a medical vocabulary.",
            "accessLevel": "Read"
        },
        "GetTranscriptionJob": {
            "url": "https://docs.aws.amazon.com/transcribe/latest/dg/API_GetTranscriptionJob.html",
            "description": "Returns information about a transcription job.",
            "accessLevel": "Read"
        },
        "GetVocabulary": {
            "url": "https://docs.aws.amazon.com/transcribe/latest/dg/API_GetVocabulary.html",
            "description": "Gets information about a vocabulary.",
            "accessLevel": "Read"
        },
        "GetVocabularyFilter": {
            "url": "https://docs.aws.amazon.com/transcribe/latest/dg/API_GetVocabularyFilter.html",
            "description": "Gets information about a vocabulary filter.",
            "accessLevel": "Read"
        },
        "ListMedicalTranscriptionJobs": {
            "url": "https://docs.aws.amazon.com/transcribe/latest/dg/API_ListMedicalTranscriptionJobs.html",
            "description": "Lists medical transcription jobs with the specified status.",
            "accessLevel": "List"
        },
        "ListMedicalVocabularies": {
            "url": "https://docs.aws.amazon.com/transcribe/latest/dg/API_ListMedicalVocabularies.html",
            "description": "Returns a list of medical vocabularies that match the specified criteria. If no criteria are specified, returns the entire list of vocabularies.",
            "accessLevel": "List"
        },
        "ListTranscriptionJobs": {
            "url": "https://docs.aws.amazon.com/transcribe/latest/dg/API_ListTranscriptionJobs.html",
            "description": "Lists transcription jobs with the specified status.",
            "accessLevel": "List"
        },
        "ListVocabularies": {
            "url": "https://docs.aws.amazon.com/transcribe/latest/dg/API_ListVocabularies.html",
            "description": "Returns a list of vocabularies that match the specified criteria. If no criteria are specified, returns the entire list of vocabularies.",
            "accessLevel": "List"
        },
        "ListVocabularyFilters": {
            "url": "https://docs.aws.amazon.com/transcribe/latest/dg/API_ListVocabularyFilters.html",
            "description": "Returns a list of vocabulary filters that match the specified criteria. If no criteria are specified, returns the at most 5 vocabulary filters.",
            "accessLevel": "List"
        },
        "StartMedicalStreamTranscription": {
            "url": "https://docs.aws.amazon.com/transcribe/latest/dg/API_streaming_StartMedicalStreamTranscription.html",
            "description": "Starts a protocol where audio is streamed to Transcribe Medical and the transcription results are streamed to your application.",
            "accessLevel": "Write"
        },
        "StartMedicalStreamTranscriptionWebSocket": {
            "url": "https://docs.aws.amazon.com/transcribe/latest/dg/API_streaming_StartMedicalStreamTranscriptionWebSocket.html",
            "description": "Starts a WebSocket where audio is streamed to Transcribe Medical and the transcription results are streamed to your application.",
            "accessLevel": "Write"
        },
        "StartMedicalTranscriptionJob": {
            "url": "https://docs.aws.amazon.com/transcribe/latest/dg/API_StartMedicalTranscriptionJob.html",
            "description": "Starts an asynchronous job to transcribe medical speech to text.",
            "accessLevel": "Write"
        },
        "StartStreamTranscription": {
            "url": "https://docs.aws.amazon.com/transcribe/latest/dg/API_streaming_StartStreamTranscription.html",
            "description": "Starts a bidirectional HTTP2 stream to transcribe speech to text in real time.",
            "accessLevel": "Write"
        },
        "StartStreamTranscriptionWebSocket": {
            "url": "https://docs.aws.amazon.com/transcribe/latest/dg/API_streaming_StartStreamTranscriptionWebSocket.html",
            "description": "Starts a websocket stream to transcribe speech to text in real time.",
            "accessLevel": "Write"
        },
        "StartTranscriptionJob": {
            "url": "https://docs.aws.amazon.com/transcribe/latest/dg/API_StartTranscriptionJob.html",
            "description": "Starts an asynchronous job to transcribe speech to text.",
            "accessLevel": "Write"
        },
        "UpdateMedicalVocabulary": {
            "url": "https://docs.aws.amazon.com/transcribe/latest/dg/API_UpdateMedicalVocabulary.html",
            "description": "Updates an existing medical vocabulary with new values. The UpdateMedicalVocabulary operation overwrites all of the existing information with the values that you provide in the request.",
            "accessLevel": "Write"
        },
        "UpdateVocabulary": {
            "url": "https://docs.aws.amazon.com/transcribe/latest/dg/API_UpdateVocabulary.html",
            "description": "Updates an existing vocabulary with new values. The UpdateVocabulary operation overwrites all of the existing information with the values that you provide in the request.",
            "accessLevel": "Write"
        },
        "UpdateVocabularyFilter": {
            "url": "https://docs.aws.amazon.com/transcribe/latest/dg/API_UpdateVocabularyFilter.html",
            "description": "Updates an existing vocabulary filter with new values. The UpdateVocabularyFilter operation overwrites all of the existing information with the values that you provide in the request.",
            "accessLevel": "Write"
        }
    };

    /**
     * Creates a new custom vocabulary that you can use to change the way Amazon Transcribe Medical handles transcription of an audio file.
     *
     * Access Level: Write
     *
     * https://docs.aws.amazon.com/transcribe/latest/dg/API_CreateMedicalVocabulary.html
     */
    public createMedicalVocabulary () {
        this.add('transcribe:CreateMedicalVocabulary');
        return this;
    }

    /**
     * Creates a new custom vocabulary that you can use to change the way Amazon Transcribe handles transcription of an audio file.
     *
     * Access Level: Write
     *
     * https://docs.aws.amazon.com/transcribe/latest/dg/API_CreateVocabulary.html
     */
    public createVocabulary () {
        this.add('transcribe:CreateVocabulary');
        return this;
    }

    /**
     * Creates a new vocabulary filter that you can use to filter out words from the transcription of an audio file generated by Amazon Transcribe
     *
     * Access Level: Write
     *
     * https://docs.aws.amazon.com/transcribe/latest/dg/API_CreateVocabularyFilter.html
     */
    public createVocabularyFilter () {
        this.add('transcribe:CreateVocabularyFilter');
        return this;
    }

    /**
     * Deletes a previously submitted medical transcription job.
     *
     * Access Level: Write
     *
     * https://docs.aws.amazon.com/transcribe/latest/dg/API_DeleteMedicalTranscriptionJob.html
     */
    public deleteMedicalTranscriptionJob () {
        this.add('transcribe:DeleteMedicalTranscriptionJob');
        return this;
    }

    /**
     * Deletes medical a vocabulary from Amazon Transcribe.
     *
     * Access Level: Write
     *
     * https://docs.aws.amazon.com/transcribe/latest/dg/API_DeleteMedicalVocabulary.html
     */
    public deleteMedicalVocabulary () {
        this.add('transcribe:DeleteMedicalVocabulary');
        return this;
    }

    /**
     * Deletes a previously submitted transcription job along with any other generated results such as the transcription, models, and so on.
     *
     * Access Level: Write
     *
     * https://docs.aws.amazon.com/transcribe/latest/dg/API_DeleteTranscriptionJob.html
     */
    public deleteTranscriptionJob () {
        this.add('transcribe:DeleteTranscriptionJob');
        return this;
    }

    /**
     * Deletes a vocabulary from Amazon Transcribe.
     *
     * Access Level: Write
     *
     * https://docs.aws.amazon.com/transcribe/latest/dg/API_DeleteVocabulary.html
     */
    public deleteVocabulary () {
        this.add('transcribe:DeleteVocabulary');
        return this;
    }

    /**
     * Deletes a vocabulary filter from Amazon Transcribe.
     *
     * Access Level: Write
     *
     * https://docs.aws.amazon.com/transcribe/latest/dg/API_DeleteVocabularyFilter.html
     */
    public deleteVocabularyFilter () {
        this.add('transcribe:DeleteVocabularyFilter');
        return this;
    }

    /**
     * Returns information about a medical transcription job.
     *
     * Access Level: Read
     *
     * https://docs.aws.amazon.com/transcribe/latest/dg/API_GetMedicalTranscriptionJob.html
     */
    public getMedicalTranscriptionJob () {
        this.add('transcribe:GetMedicalTranscriptionJob');
        return this;
    }

    /**
     * Gets information about a medical vocabulary.
     *
     * Access Level: Read
     *
     * https://docs.aws.amazon.com/transcribe/latest/dg/API_GetMedicalVocabulary.html
     */
    public getMedicalVocabulary () {
        this.add('transcribe:GetMedicalVocabulary');
        return this;
    }

    /**
     * Returns information about a transcription job.
     *
     * Access Level: Read
     *
     * https://docs.aws.amazon.com/transcribe/latest/dg/API_GetTranscriptionJob.html
     */
    public getTranscriptionJob () {
        this.add('transcribe:GetTranscriptionJob');
        return this;
    }

    /**
     * Gets information about a vocabulary.
     *
     * Access Level: Read
     *
     * https://docs.aws.amazon.com/transcribe/latest/dg/API_GetVocabulary.html
     */
    public getVocabulary () {
        this.add('transcribe:GetVocabulary');
        return this;
    }

    /**
     * Gets information about a vocabulary filter.
     *
     * Access Level: Read
     *
     * https://docs.aws.amazon.com/transcribe/latest/dg/API_GetVocabularyFilter.html
     */
    public getVocabularyFilter () {
        this.add('transcribe:GetVocabularyFilter');
        return this;
    }

    /**
     * Lists medical transcription jobs with the specified status.
     *
     * Access Level: List
     *
     * https://docs.aws.amazon.com/transcribe/latest/dg/API_ListMedicalTranscriptionJobs.html
     */
    public listMedicalTranscriptionJobs () {
        this.add('transcribe:ListMedicalTranscriptionJobs');
        return this;
    }

    /**
     * Returns a list of medical vocabularies that match the specified criteria. If no criteria are specified, returns the entire list of vocabularies.
     *
     * Access Level: List
     *
     * https://docs.aws.amazon.com/transcribe/latest/dg/API_ListMedicalVocabularies.html
     */
    public listMedicalVocabularies () {
        this.add('transcribe:ListMedicalVocabularies');
        return this;
    }

    /**
     * Lists transcription jobs with the specified status.
     *
     * Access Level: List
     *
     * https://docs.aws.amazon.com/transcribe/latest/dg/API_ListTranscriptionJobs.html
     */
    public listTranscriptionJobs () {
        this.add('transcribe:ListTranscriptionJobs');
        return this;
    }

    /**
     * Returns a list of vocabularies that match the specified criteria. If no criteria are specified, returns the entire list of vocabularies.
     *
     * Access Level: List
     *
     * https://docs.aws.amazon.com/transcribe/latest/dg/API_ListVocabularies.html
     */
    public listVocabularies () {
        this.add('transcribe:ListVocabularies');
        return this;
    }

    /**
     * Returns a list of vocabulary filters that match the specified criteria. If no criteria are specified, returns the at most 5 vocabulary filters.
     *
     * Access Level: List
     *
     * https://docs.aws.amazon.com/transcribe/latest/dg/API_ListVocabularyFilters.html
     */
    public listVocabularyFilters () {
        this.add('transcribe:ListVocabularyFilters');
        return this;
    }

    /**
     * Starts a protocol where audio is streamed to Transcribe Medical and the transcription results are streamed to your application.
     *
     * Access Level: Write
     *
     * https://docs.aws.amazon.com/transcribe/latest/dg/API_streaming_StartMedicalStreamTranscription.html
     */
    public startMedicalStreamTranscription () {
        this.add('transcribe:StartMedicalStreamTranscription');
        return this;
    }

    /**
     * Starts a WebSocket where audio is streamed to Transcribe Medical and the transcription results are streamed to your application.
     *
     * Access Level: Write
     *
     * https://docs.aws.amazon.com/transcribe/latest/dg/API_streaming_StartMedicalStreamTranscriptionWebSocket.html
     */
    public startMedicalStreamTranscriptionWebSocket () {
        this.add('transcribe:StartMedicalStreamTranscriptionWebSocket');
        return this;
    }

    /**
     * Starts an asynchronous job to transcribe medical speech to text.
     *
     * Access Level: Write
     *
     * https://docs.aws.amazon.com/transcribe/latest/dg/API_StartMedicalTranscriptionJob.html
     */
    public startMedicalTranscriptionJob () {
        this.add('transcribe:StartMedicalTranscriptionJob');
        return this;
    }

    /**
     * Starts a bidirectional HTTP2 stream to transcribe speech to text in real time.
     *
     * Access Level: Write
     *
     * https://docs.aws.amazon.com/transcribe/latest/dg/API_streaming_StartStreamTranscription.html
     */
    public startStreamTranscription () {
        this.add('transcribe:StartStreamTranscription');
        return this;
    }

    /**
     * Starts a websocket stream to transcribe speech to text in real time.
     *
     * Access Level: Write
     *
     * https://docs.aws.amazon.com/transcribe/latest/dg/API_streaming_StartStreamTranscriptionWebSocket.html
     */
    public startStreamTranscriptionWebSocket () {
        this.add('transcribe:StartStreamTranscriptionWebSocket');
        return this;
    }

    /**
     * Starts an asynchronous job to transcribe speech to text.
     *
     * Access Level: Write
     *
     * https://docs.aws.amazon.com/transcribe/latest/dg/API_StartTranscriptionJob.html
     */
    public startTranscriptionJob () {
        this.add('transcribe:StartTranscriptionJob');
        return this;
    }

    /**
     * Updates an existing medical vocabulary with new values. The UpdateMedicalVocabulary operation overwrites all of the existing information with the values that you provide in the request.
     *
     * Access Level: Write
     *
     * https://docs.aws.amazon.com/transcribe/latest/dg/API_UpdateMedicalVocabulary.html
     */
    public updateMedicalVocabulary () {
        this.add('transcribe:UpdateMedicalVocabulary');
        return this;
    }

    /**
     * Updates an existing vocabulary with new values. The UpdateVocabulary operation overwrites all of the existing information with the values that you provide in the request.
     *
     * Access Level: Write
     *
     * https://docs.aws.amazon.com/transcribe/latest/dg/API_UpdateVocabulary.html
     */
    public updateVocabulary () {
        this.add('transcribe:UpdateVocabulary');
        return this;
    }

    /**
     * Updates an existing vocabulary filter with new values. The UpdateVocabularyFilter operation overwrites all of the existing information with the values that you provide in the request.
     *
     * Access Level: Write
     *
     * https://docs.aws.amazon.com/transcribe/latest/dg/API_UpdateVocabularyFilter.html
     */
    public updateVocabularyFilter () {
        this.add('transcribe:UpdateVocabularyFilter');
        return this;
    }
}
