---
name: Toot IAM changes

on:
  # release:
  #   types: [published]
  workflow_dispatch:
    inputs:
      changelog:
        description: version to toot about
        required: true

jobs:
  toot:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # OIDC token for assuming the AWS role
      contents: read # checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: 24.x

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e1253824e5c10ff9df46874f81ed3ec929e19cfd # v6.3.0
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Toot latest version
        run: make toot
        if: ${{ github.event_name == 'release' }}
        env:
          AWS_SQS_URL: ${{ secrets.AWS_SQS_URL_MASTODON }}

      - name: Toot specified version
        run: make toot
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          CHANGELOG: ${{ github.event.inputs.changelog }}
          AWS_SQS_URL: ${{ secrets.AWS_SQS_URL_MASTODON }}
